language: java
jdk:
  - oraclejdk11
language:
  java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_script:
  - pip install --user codecov

after_success:
  - codecov
before_install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t nhanh01/myapp .
  - docker run nhanh01/myapp
# login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nhanh01/myapp
install: true
script: ./mvnw clean install
