language: java
jdk:
  - oraclejdk11
language:
  java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_script:
  - pip install --user codecov

after_success:
  - codecov
before_install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t nhanh01/myapp
install: true
script: ./mvnw clean install
