language: java
jdk:
  - oraclejdk11
language:
  java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_script:
  - pip install --user codecov

after_success:
  - codecov
before_install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t nhanh01/myapp .

# login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nhanh01/myapp
install: true
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'Docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-492397774841'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

